services:
  # Backend API Service
  - type: web
    name: deltaelmechsystems-backend
    env: node
    rootDir: .
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5002

  # Frontend Static Site
  - type: web
    name: deltaelmechsystems-frontend
    env: static
    rootDir: .
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://deltaelmechsystems-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 