# project/supabase/config.toml
project_id = "nxiykmwtkmlvefhxrumq"
[api]
enabled = true
port = 54321
schemas = ["public", "auth", "storage"]
extra_search_path = ["public", "extensions"]
[db]
port = 54322
shadow_port = 54320
[studio]
enabled = true
port = 54323
[inbucket]
enabled = true
port = 54324
[storage]
enabled = true